### ISSUE TITLE
Unix related OS support?

### ISSUE THREAD

**Issue by Fleischers** [nick-nikoliuk/webGLEngine#2]
With current instructions set in readme.md I would not be able to build your engine on some OS without involving win32. 
Any objective reasons to not provide possibilities to launch Engine on Unix-related OS without setting Virtual Win32 environment?

Maybe you could use some package manager to fulfill dependencies, `npm` for example.

If you use ts, maybe you could do this with `npm install -g typescript`, no?

By the way, if you will use some package manager to fulfill dependencies `.idea` files will be not required to keep in git repository. Generally it is bad practice to make project IDE-dependent.
Especially in days when simple and fast text editors rising in popularity among open source developers like you.

**Comment by mykola-nikoliuk** [comment]
Unix based builder was added.
The project already using npm modules (typescript), but it doesn't work on unix-based OSs, because typescript module should be installed with global flag.
So I wrote it in the readme.md.

Now to build the project you should install nodejs and typescript npm module.
After that you may use `make.bash` file to build the project.
This futures will be available in the next build or right now in "dev" branch.

Also IDE settings was removed from project (.idea folder)

Thanks for help.

**Comment by Fleischers** [comment]
You are very good at it, you made it so fast that I could not even imagine :+1: 

I will try to make a build on Ubuntu from `dev` branch and will report you if any problems occured
